# Generated by Django 5.1.1 on 2024-09-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='insturment',
            new_name='instrument',
        ),
    ]
